name: Build randopix
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - build

jobs:
  build:
    name: Build 64 Bit Linux
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Install GTK packages
      run: sudo apt install gir1.2-gtk-3.0
    - uses: actions/checkout@master
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
    - uses: jiro4989/setup-nim-action@v1.0.2
    - run: nimble build -Y
